M48
; DRILL file {KiCad (6.0.8)} date Tue Dec 13 14:59:58 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-13T14:59:58+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.5039Y-0.5157
X1.5039Y-2.4055
X2.8031Y-0.5157
X2.8031Y-2.4055
T2
X0.3794Y-2.0397
X0.3794Y-2.5397
T0
M30
